source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'TFTransparentNavigationBar_Example' do
  pod "TFTransparentNavigationBar", :path => "../"
end

target 'TFTransparentNavigationBar_Tests' do
  pod "TFTransparentNavigationBar", :path => "../"
end
